version: '3.8'

services:

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: user
      POSTGRES_DB: hibernate_examples
    ports:
      - 5432:5432

