version: '3.8'

services:

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: user
      POSTGRES_DB: hibernate_examples
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  data:
